### ISSUE TITLE
markdown image

### ISSUE THREAD

**Issue by woeishi** [woeishi/matrix-threadbot-ts#5]
> @sebescudie
> ...I just tried to capture one that had an image in it, and the resulting markdown considers them as links. which is already cool, but would it be possible to add a ! just before so that it displays it as an image? Instead of `[image.png](https://linktoimage)`, would be `![image.png](https://linktoimage)`. ofcourse one can easily edit the resulting markdown, just a suggestion :)

**Comment by woeishi** [comment]
image, audio and video messages are now converted to their corresponding html tags.
only image seems to be 'standard' as `![...` notation. therefore audio and video elements are still converted to normal md links

**Comment by sebescudie** [comment]
thanks!
